version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}-redis

  postgres:
    image: postgres:9.5-alpine
    container_name: ${APP_NAME}-postgres
    volumes:
      - "./docker-files/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "9876:5432"
    networks:
      testing_net:
        ipv4_address: 91.28.1.2

  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-webserver
    working_dir: /
    volumes:
      - "./:/ControlTime"
      - ./docker-files/nginx:/etc/nginx/conf.d
    ports:
      - "8888:8888"
      - "8085:8080"
    networks:
      testing_net:
        ipv4_address: 91.28.1.3

  php-fpm:
    build: docker-files/php-fpm
    container_name: ${APP_NAME}-php-fpm
    working_dir: /
    volumes:
      - "./:/ControlTime"
      - "./docker-files/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini"
    networks:
      testing_net:
        ipv4_address: 91.28.1.4

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 91.28.0.0/16
